builds:
  - main: main.go
    binary: mobile-icons-generator
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - mobile-icons-generator.license.md
    - README.md
brew:
  github:
    owner: beplus
    name: mobile-icons-generator

  # Dependencies of your package
  dependencies:
    - git
    - zsh

  # Packages that conflict with your package
  conflicts:
    - svn

  # Custom install script for brew. Default is 'bin.install "program"'
  install: |
    bin.install "program"