builds:
  - main: main.go
    binary: makeicon
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.build={{.Version}}
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - LICENSE
    - README.md
brew:
  github:
    owner: beplus
    name: makeicon
