builds:
  - main: main.go
    binary: makeicon
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
brew:
  github:
    owner: beplus
    name: makeicon
